package Expressions.Enums;

public enum ExpressionType {
    FUNCTION_CALL,
    STRING,
    STRING_BINARY,
    NUMBER,
    NUMBER_ADD_BINARY,
    NUMBER_MULTIPLY_BINARY,
    NUMBER_SUBTRACT_BINARY,
    NUMBER_DIVIDE_BINARY,
    VARIABLE

}
